export enum RoleAccessFormIDs {
 settings = 1,
 initialInfo,
 tags,
 articlesCategories,
 articlesList,
 articlesComments,
 servicesCategories,
 servicesList,
 projectsCategories,
 projectsList,
 users,
 contactUs,
 aboutUs,
 SocialMedia,
}
